DATA_BLOCK "DB_Alarms"
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1
   VAR 
      EStopCause : Bool;
      LevelCritCause : Bool;
      TankSensorCause : Bool;
      P1FaultCause : Bool;
      P2FaultCause : Bool;
      NoPumpCause : Bool;
      EStopLatched : Bool;
      LevelCritLatched : Bool;
      TankSensorLatched : Bool;
      P1FaultLatched : Bool;
      P2FaultLatched : Bool;
      NoPumpLatched : Bool;
      SourceLowActive : Bool;
      CriticalActive : Bool;
      ResetPulse : Bool;
      ResetEdgeMem : Bool;
   END_VAR

BEGIN

END_DATA_BLOCK